package org.embulk.input.soql;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;

import com.sforce.async.AsyncApiException;
import com.sforce.async.BatchInfo;
import com.sforce.async.BulkConnection;
import com.sforce.async.JobInfo;
import com.sforce.ws.ConnectionException;
import java.io.ByteArrayInputStream;
import java.util.Arrays;
import org.embulk.EmbulkTestRuntime;
import org.embulk.config.ConfigException;
import org.embulk.config.ConfigSource;
import org.embulk.spi.TransactionalFileInput;
import org.embulk.util.config.ConfigMapper;
import org.embulk.util.config.ConfigMapperFactory;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mockito;

public class TestSoqlFilePluginOpen {
    private static final ConfigMapperFactory CONFIG_MAPPER_FACTORY =
            ConfigMapperFactory.builder().addDefaultModules().build();
    private static final ConfigMapper CONFIG_MAPPER = CONFIG_MAPPER_FACTORY.createConfigMapper();

    @Rule public EmbulkTestRuntime runtime = new EmbulkTestRuntime();

    private ForceClient forceClient;
    private BulkConnection bulkConnection;
    private JobInfo jobInfo;
    private BatchInfo batchInfo;
    private SoqlFilePlugin plugin;

    @Before
    public void setup() {
        forceClient = mock(ForceClient.class);
        bulkConnection = mock(BulkConnection.class);
        jobInfo = mock(JobInfo.class);
        batchInfo = mock(BatchInfo.class);
        when(forceClient.getBulkConnection()).thenReturn(bulkConnection);
        when(forceClient.getJobInfo()).thenReturn(jobInfo);
        when(forceClient.getBatchInfo()).thenReturn(batchInfo);

        plugin =
                new SoqlFilePlugin() {
                    @Override
                    protected ForceClient createForceClient(PluginTask task)
                            throws AsyncApiException, ConnectionException {
                        return forceClient;
                    }
                };
    }

    @Test
    public void testOpenWithSoql() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account")
                        .set("soql", "SELECT Id,Name FROM Account");
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        when(forceClient.query(any(PluginTask.class), anyString()))
                .thenReturn(Arrays.asList("result1", "result2"));
        when(jobInfo.getId()).thenReturn("jobId");
        when(batchInfo.getId()).thenReturn("batchId");
        String csv1 = "Id,Name\n" + "1,Alice\n" + "2,Bob\n" + "3,Charlie\n";
        String csv2 = "Id,Name\n" + "4,Dave\n" + "5,Frank\n" + "6,Eve\n";
        when(bulkConnection.getQueryResultStream("jobId", "batchId", "result1"))
                .thenReturn(new ByteArrayInputStream(csv1.getBytes()));
        when(bulkConnection.getQueryResultStream("jobId", "batchId", "result2"))
                .thenReturn(new ByteArrayInputStream(csv2.getBytes()));

        TransactionalFileInput result = plugin.open(pluginTask.toTaskSource(), 0);
        assertNotNull(result);
        Mockito.verify(bulkConnection).closeJob("jobId");
        Mockito.verify(forceClient).query(pluginTask, "SELECT Id,Name FROM Account");
    }

    @Test
    public void testOpenWithAutoGeneratedSelect() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account")
                        .set("incremental", true)
                        .set("incremental_columns", Arrays.asList("Id"));
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        when(forceClient.describeObjectFieldNames("Account"))
                .thenReturn(Arrays.asList("Id", "Name"));
        when(forceClient.query(any(PluginTask.class), anyString()))
                .thenReturn(Arrays.asList("result1", "result2"));
        when(jobInfo.getId()).thenReturn("jobId");
        when(batchInfo.getId()).thenReturn("batchId");
        String csv1 = "Id,Name\n" + "1,Alice\n" + "2,Bob\n" + "3,Charlie\n";
        String csv2 = "Id,Name\n" + "4,Dave\n" + "5,Frank\n" + "6,Eve\n";
        when(bulkConnection.getQueryResultStream("jobId", "batchId", "result1"))
                .thenReturn(new ByteArrayInputStream(csv1.getBytes()));
        when(bulkConnection.getQueryResultStream("jobId", "batchId", "result2"))
                .thenReturn(new ByteArrayInputStream(csv2.getBytes()));

        TransactionalFileInput result = plugin.open(pluginTask.toTaskSource(), 0);
        assertNotNull(result);
        Mockito.verify(bulkConnection).closeJob("jobId");
        Mockito.verify(forceClient)
                .query(pluginTask, "SELECT Id,Name FROM Account ORDER BY Id ASC");
    }

    @Test
    public void testOpenWithoutSoqlAndIncrementalFalse() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account");
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        try {
            plugin.open(pluginTask.toTaskSource(), 0);
            fail("Expected exception was not thrown");
        } catch (Exception e) {
            assertTrue(e.getCause() instanceof ConfigException);
        }
    }

    @Test
    public void testOpenWithBothSoqlAndSelect() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account")
                        .set("soql", "SELECT Id,Name FROM Account")
                        .set("select", "Id,Name,Timestamp");
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        try {
            plugin.open(pluginTask.toTaskSource(), 0);
            fail("Expected exception was not thrown");
        } catch (Exception e) {
            assertTrue(e.getCause() instanceof ConfigException);
        }
    }

    @Test
    public void testOpenWithSoqlAndIncremental() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account")
                        .set("soql", "SELECT Id,Name FROM Account")
                        .set("incremental", true);
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        try {
            plugin.open(pluginTask.toTaskSource(), 0);
            fail("Expected exception was not thrown");
        } catch (Exception e) {
            assertTrue(e.getCause() instanceof ConfigException);
        }
    }

    @Test
    public void testOpenWithIncrementalAndEmptyIncrementalColumns() throws Exception {
        ConfigSource config =
                runtime.getExec()
                        .newConfigSource()
                        .set("auth_method", "oauth")
                        .set("object", "Account")
                        .set("incremental", true);
        final PluginTask pluginTask = CONFIG_MAPPER.map(config, PluginTask.class);

        try {
            plugin.open(pluginTask.toTaskSource(), 0);
            fail("Expected exception was not thrown");
        } catch (Exception e) {
            assertTrue(e.getCause() instanceof ConfigException);
        }
    }
}
