name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "zulu"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Push gem
        uses: trocco-io/push-gem-to-gpr-action@v2
        with:
          language: java
          gem-path: "./build/gems/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
